name: CICD-LongRational

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: 
      - 'Nancy/Nancy/Nancy.LongRational.csproj'
  pull_request:
    branches:
      - master
    paths: 
      - 'Nancy/Nancy/Nancy.LongRational.csproj'

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "Nancy/Nancy.sln"
      NANCY: "Nancy/Nancy/Nancy.LongRational.csproj"
      NANCY_TESTS: "Nancy/Nancy.Tests/Nancy.Tests.LongRational.csproj"

    steps:
      - uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.6

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            7.0.x
            6.0.x

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

      - name: Run tests
        run: dotnet test $NANCY_TESTS /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

      - name: Pack
        run: dotnet pack $NANCY --configuration $BUILD_CONFIG --no-restore --no-build

      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
